name: Prod Synk

on:
    workflow_dispatch:
        inputs:
            environment:
                description: 'prod'
                required: true
                default: 'prod'
                type: choice
                options:
                - prod

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
            - uses: hashicorp/setup-terraform@v4
            - name: Terraform prod
              working-directory: modules
              run: terraform init && terraform apply -auto-approve
