name: Staging synk

on:
    workflow_dispatch:
        inputs:
            environment:
                description: 'staging'
                required: true
                default: 'staging'
                type: choice
                options:
                - staging

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
            - name: Build the Docker image
              run: echo "running staging"